name: select_launcher
description: Client for the Select Launcher.
publish_to: "none"
version: 0.0.1+1
environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  feather_icons: ^1.2.0 # Beautiful icons for the app
  google_fonts: ^3.0.1 # Beautiful fonts for typography
  flutter_color_models: ^1.3.2 # Just because we wanted to use HSL
  bouncing_widget: ^2.0.0 # Helps add bounce to our UI without much fuss
  dio: ^4.0.6 # Helps in making requests to API and downloading games
  shared_preferences: ^2.0.15 # Helps in storing settings
  archive: ^3.3.2 # Helps with unzipping games
  path_provider: ^2.0.11 # Helps in getting temporary directory
  git_clone: ^1.1.0 # Helps in downloading game info
  git: ^2.2.0 # Command line wrapper to pull git repo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
