[package]
name = "updater"
version = "0.1.0"
edition = "2021"
authors = ["Select Studios <email>"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.20.1"
eframe = "0.20.1"
tracing-subscriber = "0.3"