// Generated by https://quicktype.io

export default interface GameInfo {
  name: string;
  description: string;
  downloadName: string;
  image: {
    icon: string;
  };
  publisher: string;
  developer: string;
  tags: string[];
  platforms: string[];
  price: number | "free";
  verified: boolean;
}

export interface Image {
  icon: string;
}
