// Generated by https://quicktype.io

export default interface GameInfo {
  name: string;
  downloadName: string;
  description: string;
  image: Image;
  tags: string[];
}

export interface Image {
  icon: string;
}
